### ISSUE TITLE
Mailing list subscription form

### ISSUE THREAD

**Issue by OlliKousa** [aknutas/doit-website#24]
Mailchimp subscription form currently implemented at doittest.parvus.fi in the bottom of the page. 

Other locations or layouts are also possible, but in the footer it could be on every page without disturbing the user experience.

**Comment by OlliKousa** [comment]
Current form looks like this:
![image](https://user-images.githubusercontent.com/17763766/54996282-276d3500-4fc9-11e9-9bab-634e843389a3.png)
Would it be better before the footer? And what pages should it be at? @aknutas

**Comment by aknutas** [comment]
Hi,
   I think it is ok if we add the subscription form only to the front page. And I believe we could go with a layout like this.

-Antti
