### ISSUE TITLE
Fix scheduling errors

### ISSUE THREAD

**Issue by OlliKousa** [aknutas/doit-website#25]
The block scheduling works correctly, but it does not reset the cache, which is why chat was not displayed. 
Possible solutions: 
1) Enable time-critical modules manually. 
2) Change cache expiry to 5-15 minutes.

**Comment by aknutas** [comment]
How about making cache expiry very short, then, and scheduling things with an appropriate safety margin?

**Comment by OlliKousa** [comment]
Cache renews now every 15min and chat is scheduled to display 30min before start. I'll monitor the next implementation on stand-by and make sure it works.

**Comment by aknutas** [comment]
Ok. Let's see how it works in the next pilot session.

**Comment by OlliKousa** [comment]
Still doesn't seem to work. Scheduler is doing good job, but for some reason the cache isn't refreshing. Needs further investigation.

**Comment by aknutas** [comment]
Thanks for the update. Let's try to make this a priority task.

**Comment by OlliKousa** [comment]
Now it seems to be working. I set cron to rebuild cache ~5mins after the content is scheduled, so it should be online well in advance. (Assuming that I've set the cron correctly, picture of the setup attached)
![image](https://user-images.githubusercontent.com/17763766/55638299-260ceb00-57c7-11e9-9e84-4b0c7229491a.png)

**Comment by aknutas** [comment]
Good job. Let's verify that it works in the next online pilot and if everything is ok, let's close the ticket.

**Comment by OlliKousa** [comment]
Seems to work now! I had the numbers off by one for Tuesday (silly brainfart), but I fixed that and the chat appeared now properly on time.
