### ISSUE TITLE
Layouts: logo of the partners (same size for all looks very unbalanced)

### ISSUE THREAD

**Issue by aknutas** [aknutas/doit-website#5]

**Comment by OlliKousa** [comment]
Katottiin Jyrin kanssa, eikä oikeen keksitty miten nuo vois olla paremmin.

**Comment by aknutas** [comment]
Would it be possible to make sure that the centre points of all logos in https://www.doit-europe.net/project are balanced? Now for example LUT appears to be higher than WaaG or salzburg.

**Comment by OlliKousa** [comment]
Currently graphic designer is taking a quick look at this. Also, should CoC still be in this? Or maybe the new partner that replaced them? @aknutas

**Comment by aknutas** [comment]
@OlliKousa you are right that CoC should be replaced in the logo. I'll ask the project coordinator about this.

**Comment by OlliKousa** [comment]
A new version of the wall: 
![doit_partner_logowall](https://user-images.githubusercontent.com/17763766/54996220-00166800-4fc9-11e9-91c5-7fe200ba67fa.jpg)

**Comment by OlliKousa** [comment]
The picture from Salzburg does not really work: https://doittest.parvus.fi/project 
But I assume the essential point was that all partner logos should be treated equally and given the same amount of space. 
I'm not sure if this is a problem worth solving, although I agree with the initial point, they do look unbalanced.

**Comment by OlliKousa** [comment]
Figured out a smart compromise. Because the wide image wouldn't work on mobile devices at all, I've made a responsible solution. The original image displays on smaller screens, whereas the new wider picture displays on larger screens with negative margin.

**Comment by aknutas** [comment]
Great!
