### ISSUE TITLE
Events page 

### ISSUE THREAD

**Issue by aknutas** [aknutas/doit-website#7]

**Comment by OlliKousa** [comment]
Changed the issue to refer more generally to the events page, as we are now experimenting with other implementation directions. Latest suggestion is to utilize time.ly to create a customizable calendar widget. Different options seen here: https://doittest.parvus.fi/calendar

**Comment by OlliKousa** [comment]
This is now published. Unfortunately the font size is quite small for some reason. Time.ly doesn't allow customized CSS in the free version. Unlocking customizable header and footer costs huge amount of 1,49$/month.

**Comment by aknutas** [comment]
Ok, thanks. Let's see if we need to move to a commercial version.
